###服务启动端口号
server:
  port: 8210
spring:
  application:
    name:  app-kevin-mycat
  datasource:
    ###可读数据源
    select:
      jdbc-url: jdbc:mysql://kevin2:8066/mycat_testdb
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: user
    ####可写数据源  
    update:
      jdbc-url: jdbc:mysql://kevin2:8066/mycat_testdb
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
   ##### 当前会员服务注册到eureka服务地址
      defaultZone: http://kevin2:8080/eureka
freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
mvc: 
    static-path-pattern: /static/**

     