app:
  # 与apollo的admin管理界面添加的 appId 一致
  id: demo-service-shardingjdbc
apollo:
  # meta的url
  meta: http://kevin2:8080
  bootstrap:
    enabled: true
    # 从 namespace 中获取配置, 多个以逗号隔开, namespace的配置非properties格式的需要加后缀名
    namespaces: application,eureka
