spring:
  application:
    name: app-kevin-cache-redis
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000        #最大并发数
      max-connections: 20000   #接受和处理的最大连接数
      min-SpareThreads: 1000     #初始化时创建的线程数
      acceptCount: 0         #可以放到处理队列中的请求数
  redis:
    database: 0
    host: kevin1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: 123456
    port: 6379
    max: 
      total: 8
      idle: 0
      waitmillis: -1
    sentinel: 
      database: 0
      host: kevin4
      password: 123456
      port: 26379
eureka:
  client:
    service-url:
   ##### 当前会员服务注册到eureka服务地址
      defaultZone: http://kevin2:8080/eureka
server:
  port: 8510

spring.main.allow-bean-definition-overriding: true
