server:
  port: 9000
spring:
  application:
    name: springcloud-stream-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.97.123:9092         #Kafka的消息中间件服务器
          zk-nodes: 172.16.97.123:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output        
            destination: springcloud-stream-consumer-test    #消息发往的目的地            
            content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
eureka:
  client:
    service-url:
   ##### 当前会员服务注册到eureka服务地址
      defaultZone: http://localhost:8000/eureka,http://localhost:8001/eureka
      

