###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)  
spring:
  application:
    name:  app-kevin-zuul
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
###数据库相关连接      
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.97.123:3306/kevin_gateway?useUnicode=true&characterEncoding=UTF-8
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://kevin2:8080/eureka


### 配置网关反向代理    
zuul:
  routes:
    api-a:
     ### 以 /api-mycat/访问转发
      path: /api-mycat/**
      serviceId: app-kevin-mycat
    api-b:
        ### 以 /api-shardingjdbc/访问转发
      path: /api-shardingjdbc/**
      serviceId: app-kevin-shardingjdbc
swagger:
  base-package: com.kevin.basics.zuul.controller
kevin: 
  zuul: 
    swagger: 
      document: 微服务展示项目网关服务
      